name: Terraform Plan Staging
on:
  pull_request:
    paths:
      - "terragrunt/aws/**"
      - "terragrunt/env/staging/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/root.hcl"
      - ".github/workflows/tf-plan-staging.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.10.5
  TERRAGRUNT_VERSION: 0.73.13
  TF_SUMMARIZE_VERSION: 0.3.5
  TF_INPUT: false
  TF_VAR_hosted_zone_id: ${{ secrets.STAGING_HOSTED_ZONE_ID }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@2aee21aebfddefac5839497648a36a9f84342d8b
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@cc15ce9039f6c37c592fb9930b70466b229d2e9b # v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::211125499457:role/cra-arc-ucdg-gcau-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          comment-delete: true
          comment-title: "Staging"
          directory: "terragrunt/env/staging"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
